### ISSUE TITLE
UI-improvement: Move the `play` button from the editing tool bar to the view buttons one line above

### ISSUE THREAD

**Issue by janklostermann** [personalizedrefrigerator/joplin-plugin-revealjs-slides#3]
First of all: Thanks a lot for your cool plugin!

**Is your feature request related to a problem? Please describe.**
The `play` button to start the slideshow is located among the markdown formating buttons.
Joplin's "Toggle editor layout" button and other 'view buttons' from other plugins are placed one level higher, 
e.g. the "Show as Mindmap" from the [Markmap](https://git.fomin.site/daniel/joplin-markmap) plugin, or "Show/Hide Graph View" from [Link Graph UI](https://github.com/treymo/joplin-link-graph). 

See right from the "Note Properties" icon on the screenshot:
![image](https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/assets/11610051/49c8157d-04f3-4420-a516-11836ac4193b)

**Describe the solution you'd like**
I would prefer to find all buttons that relate to the way of displaying the note (or info about it) at one place. 
Therefore moving your button up to where the others are, would be cool. 

**Describe alternatives you've considered**
Just live with it as it is... (as I cannot change it myself, I guess)

**Comment by personalizedrefrigerator** [comment]
Good idea!

I hope to add support for the equivalent on mobile first (currently mobile plugins can only add markdown toolbar buttons), but after that, this seems like a good change.

**Comment by personalizedrefrigerator** [comment]
Resolved by 2c9d16dc5621625fd4c7eedc720b96a91beaf7ec.
